version: "2.4"
services:
  client:
    build:
      context: ./client
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - client_node_modules:/usr/app/node_modules
      - ./client:/usr/app

  posts:
    build:
      context: ./posts
      target: dev
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - posts_node_modules:/usr/app/node_modules
      - ./posts:/usr/app

  comments:
    build:
      context: ./comments
      target: dev
    ports:
      - "127.0.0.1:4001:4001"
    volumes:
      - comments_node_modules:/usr/app/node_modules
      - ./comments:/usr/app

  event-bus:
    build:
      context: ./event-bus
      target: dev
    ports:
      - "127.0.0.1:4005:4005"
    volumes:
      - event-bus_node_modules:/usr/app/node_modules
      - ./event-bus:/usr/app

  query:
    build:
      context: ./query
      target: dev
    ports:
      - "127.0.0.1:4002:4002"
    volumes:
      - query_node_modules:/usr/app/node_modules
      - ./query:/usr/app

  moderation:
    build:
      context: ./moderation
      target: dev
    ports:
      - "127.0.0.1:4003:4003"
    volumes:
      - moderation_node_modules:/usr/app/node_modules
      - ./moderation:/usr/app

volumes:
  client_node_modules:
  posts_node_modules:
  comments_node_modules:
  query_node_modules:
  event-bus_node_modules:
  moderation_node_modules:
