POST http://localhost:4001/posts/123/comments
Content-Type: application/json

{
  "content": "Hello, this is from the comments"
}

###

POST http://localhost:4001/posts/124/comments 
Content-Type: application/json

{
  "content": "New from 124"
}

###

GET http://localhost:4001/posts/123/comments

###

GET http://localhost:4001/posts/124/comments 
Content-Type: application/json