// WIth k8s
// use 'minikube ip' and 'kubectl get services' for address
// POST http://192.168.49.2:30157/posts
// Content-Type: appiclation/json
POST http://localhost:4000/posts
Content-Type: application/json

{
  "title": "First Post"
}

###

// With k8s
// GET http://192.168.49.2:30157/posts
GET http://localhost:4000/posts
